export const FETCH_VENUES = 'FETCH_VENUES';
export const ADD_PARTICIPANT = 'ADD_PARTICIPANT';
export const INCREASE_PARTICIPANT_VOTE = 'INCREASE_PARTICIPANT_VOTE';
export const CLEAN_PARTICIPANTS = 'CLEAN_PARTICIPANTS';